schema_version: 1

context:
  version: "0.21.1"

package:
  name: sos-bash
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/sos-bash/sos_bash-${{ version }}.tar.gz
  sha256: c8fe4680e1ca33c22b54888506833581884a0aa211977c12375fff16c77c1ca0

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python =${{ python_min }}
    - setuptools
  run:
    - sos-notebook >=0.19.4
    - calysto_bash
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - sos_bash
      pip_check: true
  - requirements:
      run:
        - pip
        - python =${{ python_min }}
    script:
      - pip check

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: SoS language module for bash
  homepage: https://github.com/vatlab/sos-bash
  repository: https://github.com/vatlab/sos-bash
  documentation: https://vatlab.github.io/sos-docs/

extra:
  recipe-maintainers:
    - danielnachun
    - BoPeng
